select * from Cart;

CREATE TABLE Cart (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	UserId INTEGER NOT NULL,
	CONSTRAINT FK_Cart_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
);

CREATE TABLE CartDisc (
	Id INTEGER NOT NULL PRIMARY KEY IDENTITY,
	CartId INTEGER NOT NULL,
	DiscId INTEGER NOT NULL,
	UserId INTEGER NOT NULL,
	CONSTRAINT FK_CartDisc_Cart FOREIGN KEY (CartId) REFERENCES Cart(Id),
	CONSTRAINT FK_CartDisc_Discs FOREIGN KEY (DiscId) REFERENCES Discs(Id),
	CONSTRAINT FK_CartDisc_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
);